import type { CVData } from './src/lib/parsePdf';

export const SEED_CV_DATA: CVData = {
  name: 'YOUR NAME',
  title: 'Fullstack Developer',
  contact: {
    email: '',
    phone: '',
    linkedin: '',
    github: '',
    location: 'Remote',
  },
  summary: '',
  skills: [
    { name: 'JavaScript (ES6+)', category: 'Frontend (Main Experience)' },
    { name: 'TypeScript', category: 'Frontend (Main Experience)' },
    { name: 'React.js', category: 'Frontend (Main Experience)' },
    { name: 'Next.js (App Router & Pages Router)', category: 'Frontend (Main Experience)' },
    { name: 'Tailwind CSS', category: 'Frontend (Main Experience)' },
    { name: 'SASS', category: 'Frontend (Main Experience)' },
    { name: 'ShadCN UI', category: 'Frontend (Main Experience)' },
    { name: 'Flowbite', category: 'Frontend (Main Experience)' },
    { name: 'CSS-in-JS', category: 'Frontend (Main Experience)' },
    { name: 'Responsive Design', category: 'Frontend (Main Experience)' },
    { name: 'Web Performance Optimization', category: 'Frontend (Main Experience)' },
    { name: 'SEO', category: 'Frontend (Main Experience)' },
    { name: 'Accessibility (a11y)', category: 'Frontend (Main Experience)' },
    { name: 'Vite', category: 'Frontend (Main Experience)' },
    { name: 'Webpack', category: 'Frontend (Main Experience)' },
    { name: 'Node.js', category: 'Backend and Database' },
    { name: 'Express.js', category: 'Backend and Database' },
    { name: 'NestJS', category: 'Backend and Database' },
    { name: 'TypeORM', category: 'Backend and Database' },
    { name: 'PostgreSQL', category: 'Backend and Database' },
    { name: 'Supabase', category: 'Backend and Database' },
    { name: 'RESTful API Design', category: 'Backend and Database' },
    { name: 'Backend Architecture', category: 'Backend and Database' },
    { name: 'Git', category: 'Tools and Workflow' },
    { name: 'GitHub', category: 'Tools and Workflow' },
    { name: 'Version Control', category: 'Tools and Workflow' },
    { name: 'Code Reviews', category: 'Tools and Workflow' },
    { name: 'Figma', category: 'Tools and Workflow' },
    { name: 'Adobe XD', category: 'Tools and Workflow' },
    { name: 'WordPress (Headless CMS with ACF)', category: 'Tools and Workflow' },
    { name: 'npm', category: 'Tools and Workflow' },
    { name: 'Prettier', category: 'Tools and Workflow' },
    { name: 'Docker (Basic)', category: 'Tools and Workflow' },
    { name: 'CI/CD Concepts', category: 'Tools and Workflow' },
    { name: 'Spanish (Native)', category: 'Languages' },
    { name: 'English', category: 'Languages' },
  ],
  experience: [
    {
      company: 'Valere',
      position: 'Fullstack Developer',
      startDate: '07/2025',
      endDate: null,
      location: 'Remote',
      description: [
        'Acted as a technical point of contact for architectural decisions, ensuring scalability and long-term maintainability for both frontend and backend systems.',
        'Developed and maintained backend APIs using NestJS and Python, optimizing relational databases (PostgreSQL/Supabase) for production-ready cloud environments.',
        'Streamlined data extraction and processing pipelines using serverless solutions (Azure Functions), significantly reducing manual overhead and improving system efficiency.',
        'Led the development of scalable and flexible landing pages using Next.js, focused on high performance and seamless user experience.',
      ],
      technologies: 'NestJS, TypeORM, PostgreSQL, Supabase, Google Cloud Platform (Cloud SQL), Azure Functions, Python',
    },
    {
      company: 'Flare BBDO',
      position: 'Frontend Developer',
      startDate: '10/2022',
      endDate: '12/2025',
      location: 'Bogotá, Colombia',
      description: [
        'Developed an internal platform using Next.js to automate email template creation, resulting in a 50% reduction in delivery times and streamlining workflows across the marketing team.',
        'Integrated Headless CMS solutions (ACF) to empower content managers, enabling them to make updates independently and reducing engineering support requests by 40%.',
        'Designed and maintained a library of reusable UI components using React and Tailwind CSS, ensuring visual consistency and accelerating development cycles for high-traffic projects.',
        'Acted as a bridge between creative designers and technical teams, translating visual requirements into performant and accessible code.',
      ],
      technologies: 'Next.js, React, Tailwind CSS, ShadCN, Headless CMS (ACF), Git, Vite',
    },
    {
      company: 'Ariatel, SARL',
      position: 'Frontend Developer',
      startDate: '07/2021',
      endDate: '07/2022',
      location: 'Bogotá, Colombia',
      description: [
        'Modernized legacy codebases by migrating class-based components to functional components using React and TypeScript, significantly improving code maintainability and team velocity.',
        'Optimized the build process for a Microfrontend architecture by configuring Webpack, eliminating manual deployment tasks and achieving a 30% performance improvement.',
        'Partnered with backend engineering teams to identify and resolve bottlenecks, resulting in a 20% increase in overall application speed and a smoother user experience.',
      ],
      technologies: 'React, TypeScript, Webpack, Git',
    },
  ],
  education: [],
};
